#!/usr/bin/bash

if [ "$#" != "1" ]; then
   echo "Usage: deploy <version-number>"
   exit 1
fi

aws s3 cp ec2-scripts/ec2-prod-$1.sh s3://edu.au.cc.image-gallery-config11
aws s3 cp nginx/nginx.conf s3://edu.au.cc.image-gallery-config11/nginx/nginx.conf
aws s3 cp nginx/default.d/image_gallery.conf s3://edu.au.cc.image-gallery-config11/nginx/default.d/image_gallery.conf
